### ISSUE TITLE
Differentiate the versions of each message

### ISSUE THREAD

**Issue by romainreignier** [daedaleanai/ublox#3]
There are several messages with the same Class ID and Message ID but a different length.
CFG-MSG for example:
![image](https://user-images.githubusercontent.com/8845664/103524547-0b751380-4e7e-11eb-8782-047bcfc7ac3a.png)

The `messages.go` adds a numeric suffix to differentiate them, but in `decode.go`, the [`switch`](https://github.com/daedaleanai/ublox/blob/c68b71c8f5026c4d0f365ccc2fad680bf2f7036b/ubx/decode.go#L47) cannot differentiate them.
I think that a `Length()` method should be added to the [`Message`](https://github.com/daedaleanai/ublox/blob/c68b71c8f5026c4d0f365ccc2fad680bf2f7036b/ubx/messages.go#L3) interface.

But the `Length` field in the XML file is not easy to handle.

What are your thoughts about this issue and how do you want to handle it?

By the way, how is the xml file generated?

**Comment by romainreignier** [comment]
Can be tested with:

```go
package ubx

import (
	"bytes"
	"reflect"
	"testing"
)

func TestCanDecodeCorrectCfgMsgType(t *testing.T) {
	originalMsg := CfgMsg2{MsgClass: 0xF0, MsgID: 0x9} // GBS
	var b bytes.Buffer
	err := Encode(&b, originalMsg)
	if err != nil {
		t.Error(err)
	}

	msg, err := Decode(b.Bytes())
	if err != nil {
		t.Error(err)
	}
	pointerToOriginalMsg := &originalMsg
	if reflect.TypeOf(msg) != reflect.TypeOf(pointerToOriginalMsg) {
		t.Error("Bad msg type")
	}
	cfgMsg := msg.(*CfgMsg2)
	if cfgMsg.MsgClass != 0xF0 {
		t.Errorf("Bad MsgClass. Should be 0xF0, actually is: %xd", cfgMsg.MsgClass)
	}
	if cfgMsg.MsgID != 0x9 {
		t.Errorf("Bad MsgID. Should be 0x9, actually is: %xd", cfgMsg.MsgID)
	}
}
```

**Comment by lvdlvd** [comment]
the xml was 'generated' by one of my staff putting in a month of monk's work transliterating the pdf and looking at the bitfield pictures. ublox claimed there was no internal source, or they just didnt want to make it available.  given the quality of thee protocol design that doesnt surprise me.

**Comment by romainreignier** [comment]
> the xml was 'generated' by one of my staff putting in a month of monk's work transliterating the pdf and looking at the bitfield pictures

Ouch! That's a large amount of work!

**Comment by lvdlvd** [comment]
yep, esp when compared to me writing the code to use it which was far less.

Op ma 4 jan. 2021 om 12:05 schreef Romain Reignier <notifications@github.com

**Comment by romainreignier** [comment]
I have tried the `genmsg` branch and the issue seems to be already resolved.
